This is a personal collection of [[https://guix.gnu.org][GNU Guix]] package definitions.

* Packages

This channel provides packages: 
- ~geant4~
- ~geant4-vis~
- ~python-radcomp~
 
** geant4

~geant4~ is [[https://geant4.web.cern.ch][Geant4]] without support for visualisation.

Versions provided:
- 11.1.2
- 11.1.1

Minimal environment:
  
#+begin_src shell

  guix shell geant4 cmake make gcc-toolchain

  # copy an example app
  INSTALL_DIR=$(guix build geant4)
  cp -rf $INSTALL_DIR/share/Geant4/examples/basic/B1 .

  # the store is read only
  chmod -R 751 B1/

  # the usual
  cd B1
  mkdir build
  cd build
  cmake ..; make
  ./exampleB1 run1.mac

#+end_src

NB. Do not source =$INSTALL_DIR/bin/geant4.sh=.

** geant4-vis

~geant4-vis~ is [[https://geant4.web.cern.ch][Geant4]] including support for visualisation with OpenGL and Qt.

Versions provided:
- 11.1.2
- 11.1.1

Minimal environment:

#+begin_src shell

  guix shell geant4-vis cmake make gcc-toolchain mesa

  # copy an example app
  INSTALL_DIR=$(guix build geant4-vis)
  cp -rf $INSTALL_DIR/share/Geant4/examples/basic/B1 .

  # the store is read only
  chmod -R 751 B1/

  # the usual
  cd B1
  mkdir build
  cd build
  cmake ..; make
  ./exampleB1

#+end_src

NB. Do not source =$INSTALL_DIR/bin/geant4.sh=.

** python-radcomp

~python-radcomp~ is the Python [[https://github.com/jakeforster/radcomp][package]].

Versions provided:
- 0.2.0

Example environment:

#+begin_src shell

  guix shell python python-radcomp python-tornado 
  export MPLBACKEND=WebAgg

#+end_src

* Usage

To use this channel, add it to your configuration in =~/.config/guix/channels.scm=, e.g.:

#+begin_src scheme

  (cons* (channel
           (name 'jforst)
           (url "https://github.com/jakeforster/guix-channel")
           (branch "master")
           (introduction
            (make-channel-introduction
             "ff010b01733bf1a0f2dd5f0d575730d03a107fe4"
             (openpgp-fingerprint
              "CFE9 8893 632A 4A6C 43E6  BF38 C6C6 5219 AA51 07F3"))))
         %default-channels)

#+end_src

Alternatively, you can install a package from this channel by temporarily adding the channel to your load path. E.g., in a one-off environment:

#+begin_src shell

  git clone https://github.com/jakeforster/guix-channel.git
  guix shell -L ./guix-channel geant4 cmake make gcc-toolchain

#+end_src

